package net.xytra.sylvarbo.persistent.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.List;

import org.apache.cayenne.BaseDataObject;
import org.apache.cayenne.exp.Property;

import net.xytra.sylvarbo.persistent.PersonEvent;
import net.xytra.sylvarbo.persistent.PersonIdentity;
import net.xytra.sylvarbo.persistent.Relationship;

/**
 * Class _Person was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Person extends BaseDataObject {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<List<PersonEvent>> PERSON_EVENTS = Property.create("personEvents", List.class);
    public static final Property<List<PersonIdentity>> PERSON_IDENTITIES = Property.create("personIdentities", List.class);
    public static final Property<PersonIdentity> PRIMARY_IDENTITY = Property.create("primaryIdentity", PersonIdentity.class);
    public static final Property<Relationship> RELATIONSHIP_AS_CHILD = Property.create("relationshipAsChild", Relationship.class);
    public static final Property<List<Relationship>> RELATIONSHIPS_AS_PRIMARY = Property.create("relationshipsAsPrimary", List.class);
    public static final Property<List<Relationship>> RELATIONSHIPS_AS_SECONDARY = Property.create("relationshipsAsSecondary", List.class);


    protected Object personEvents;
    protected Object personIdentities;
    protected Object primaryIdentity;
    protected Object relationshipAsChild;
    protected Object relationshipsAsPrimary;
    protected Object relationshipsAsSecondary;

    public void addToPersonEvents(PersonEvent obj) {
        addToManyTarget("personEvents", obj, true);
    }

    public void removeFromPersonEvents(PersonEvent obj) {
        removeToManyTarget("personEvents", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PersonEvent> getPersonEvents() {
        return (List<PersonEvent>)readProperty("personEvents");
    }

    public void addToPersonIdentities(PersonIdentity obj) {
        addToManyTarget("personIdentities", obj, true);
    }

    public void removeFromPersonIdentities(PersonIdentity obj) {
        removeToManyTarget("personIdentities", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<PersonIdentity> getPersonIdentities() {
        return (List<PersonIdentity>)readProperty("personIdentities");
    }

    public void setPrimaryIdentity(PersonIdentity primaryIdentity) {
        setToOneTarget("primaryIdentity", primaryIdentity, true);
    }

    public PersonIdentity getPrimaryIdentity() {
        return (PersonIdentity)readProperty("primaryIdentity");
    }

    public void setRelationshipAsChild(Relationship relationshipAsChild) {
        setToOneTarget("relationshipAsChild", relationshipAsChild, true);
    }

    public Relationship getRelationshipAsChild() {
        return (Relationship)readProperty("relationshipAsChild");
    }

    public void addToRelationshipsAsPrimary(Relationship obj) {
        addToManyTarget("relationshipsAsPrimary", obj, true);
    }

    public void removeFromRelationshipsAsPrimary(Relationship obj) {
        removeToManyTarget("relationshipsAsPrimary", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Relationship> getRelationshipsAsPrimary() {
        return (List<Relationship>)readProperty("relationshipsAsPrimary");
    }

    public void addToRelationshipsAsSecondary(Relationship obj) {
        addToManyTarget("relationshipsAsSecondary", obj, true);
    }

    public void removeFromRelationshipsAsSecondary(Relationship obj) {
        removeToManyTarget("relationshipsAsSecondary", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Relationship> getRelationshipsAsSecondary() {
        return (List<Relationship>)readProperty("relationshipsAsSecondary");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "personEvents":
                return this.personEvents;
            case "personIdentities":
                return this.personIdentities;
            case "primaryIdentity":
                return this.primaryIdentity;
            case "relationshipAsChild":
                return this.relationshipAsChild;
            case "relationshipsAsPrimary":
                return this.relationshipsAsPrimary;
            case "relationshipsAsSecondary":
                return this.relationshipsAsSecondary;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "personEvents":
                this.personEvents = val;
                break;
            case "personIdentities":
                this.personIdentities = val;
                break;
            case "primaryIdentity":
                this.primaryIdentity = val;
                break;
            case "relationshipAsChild":
                this.relationshipAsChild = val;
                break;
            case "relationshipsAsPrimary":
                this.relationshipsAsPrimary = val;
                break;
            case "relationshipsAsSecondary":
                this.relationshipsAsSecondary = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.personEvents);
        out.writeObject(this.personIdentities);
        out.writeObject(this.primaryIdentity);
        out.writeObject(this.relationshipAsChild);
        out.writeObject(this.relationshipsAsPrimary);
        out.writeObject(this.relationshipsAsSecondary);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.personEvents = in.readObject();
        this.personIdentities = in.readObject();
        this.primaryIdentity = in.readObject();
        this.relationshipAsChild = in.readObject();
        this.relationshipsAsPrimary = in.readObject();
        this.relationshipsAsSecondary = in.readObject();
    }

}
