package net.xytra.sylvarbo.persistent.auto;

import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.Date;
import java.util.List;

import org.apache.cayenne.exp.Property;

import net.xytra.common.cayenne.persistent.AbstractModifiable;
import net.xytra.common.cayenne.persistent.User;
import net.xytra.sylvarbo.persistent.Person;
import net.xytra.sylvarbo.persistent.RelationshipEvent;

/**
 * Class _Relationship was generated by Cayenne.
 * It is probably a good idea to avoid changing this class manually,
 * since it may be overwritten next time code is regenerated.
 * If you need to make any customizations, please use subclass.
 */
public abstract class _Relationship extends AbstractModifiable {

    private static final long serialVersionUID = 1L; 

    public static final String ID_PK_COLUMN = "ID";

    public static final Property<Date> CREATED_DTM = Property.create("createdDtm", Date.class);
    public static final Property<Date> MODIFIED_DTM = Property.create("modifiedDtm", Date.class);
    public static final Property<String> TYPE = Property.create("type", String.class);
    public static final Property<List<Person>> CHILDREN = Property.create("children", List.class);
    public static final Property<List<RelationshipEvent>> EVENTS = Property.create("events", List.class);
    public static final Property<Person> PRIMARY_PARENT = Property.create("primaryParent", Person.class);
    public static final Property<Person> SECONDARY_PARENT = Property.create("secondaryParent", Person.class);
    public static final Property<User> USER_CREATED = Property.create("userCreated", User.class);
    public static final Property<User> USER_MODIFIED = Property.create("userModified", User.class);

    protected Date createdDtm;
    protected Date modifiedDtm;
    protected String type;

    protected Object children;
    protected Object events;
    protected Object primaryParent;
    protected Object secondaryParent;
    protected Object userCreated;
    protected Object userModified;

    public void setCreatedDtm(Date createdDtm) {
        beforePropertyWrite("createdDtm", this.createdDtm, createdDtm);
        this.createdDtm = createdDtm;
    }

    public Date getCreatedDtm() {
        beforePropertyRead("createdDtm");
        return this.createdDtm;
    }

    public void setModifiedDtm(Date modifiedDtm) {
        beforePropertyWrite("modifiedDtm", this.modifiedDtm, modifiedDtm);
        this.modifiedDtm = modifiedDtm;
    }

    public Date getModifiedDtm() {
        beforePropertyRead("modifiedDtm");
        return this.modifiedDtm;
    }

    public void setType(String type) {
        beforePropertyWrite("type", this.type, type);
        this.type = type;
    }

    public String getType() {
        beforePropertyRead("type");
        return this.type;
    }

    public void addToChildren(Person obj) {
        addToManyTarget("children", obj, true);
    }

    public void removeFromChildren(Person obj) {
        removeToManyTarget("children", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<Person> getChildren() {
        return (List<Person>)readProperty("children");
    }

    public void addToEvents(RelationshipEvent obj) {
        addToManyTarget("events", obj, true);
    }

    public void removeFromEvents(RelationshipEvent obj) {
        removeToManyTarget("events", obj, true);
    }

    @SuppressWarnings("unchecked")
    public List<RelationshipEvent> getEvents() {
        return (List<RelationshipEvent>)readProperty("events");
    }

    public void setPrimaryParent(Person primaryParent) {
        setToOneTarget("primaryParent", primaryParent, true);
    }

    public Person getPrimaryParent() {
        return (Person)readProperty("primaryParent");
    }

    public void setSecondaryParent(Person secondaryParent) {
        setToOneTarget("secondaryParent", secondaryParent, true);
    }

    public Person getSecondaryParent() {
        return (Person)readProperty("secondaryParent");
    }

    public void setUserCreated(User userCreated) {
        setToOneTarget("userCreated", userCreated, true);
    }

    public User getUserCreated() {
        return (User)readProperty("userCreated");
    }

    public void setUserModified(User userModified) {
        setToOneTarget("userModified", userModified, true);
    }

    public User getUserModified() {
        return (User)readProperty("userModified");
    }

    @Override
    public Object readPropertyDirectly(String propName) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch(propName) {
            case "createdDtm":
                return this.createdDtm;
            case "modifiedDtm":
                return this.modifiedDtm;
            case "type":
                return this.type;
            case "children":
                return this.children;
            case "events":
                return this.events;
            case "primaryParent":
                return this.primaryParent;
            case "secondaryParent":
                return this.secondaryParent;
            case "userCreated":
                return this.userCreated;
            case "userModified":
                return this.userModified;
            default:
                return super.readPropertyDirectly(propName);
        }
    }

    @Override
    public void writePropertyDirectly(String propName, Object val) {
        if(propName == null) {
            throw new IllegalArgumentException();
        }

        switch (propName) {
            case "createdDtm":
                this.createdDtm = (Date)val;
                break;
            case "modifiedDtm":
                this.modifiedDtm = (Date)val;
                break;
            case "type":
                this.type = (String)val;
                break;
            case "children":
                this.children = val;
                break;
            case "events":
                this.events = val;
                break;
            case "primaryParent":
                this.primaryParent = val;
                break;
            case "secondaryParent":
                this.secondaryParent = val;
                break;
            case "userCreated":
                this.userCreated = val;
                break;
            case "userModified":
                this.userModified = val;
                break;
            default:
                super.writePropertyDirectly(propName, val);
        }
    }

    private void writeObject(ObjectOutputStream out) throws IOException {
        writeSerialized(out);
    }

    private void readObject(ObjectInputStream in) throws IOException, ClassNotFoundException {
        readSerialized(in);
    }

    @Override
    protected void writeState(ObjectOutputStream out) throws IOException {
        super.writeState(out);
        out.writeObject(this.createdDtm);
        out.writeObject(this.modifiedDtm);
        out.writeObject(this.type);
        out.writeObject(this.children);
        out.writeObject(this.events);
        out.writeObject(this.primaryParent);
        out.writeObject(this.secondaryParent);
        out.writeObject(this.userCreated);
        out.writeObject(this.userModified);
    }

    @Override
    protected void readState(ObjectInputStream in) throws IOException, ClassNotFoundException {
        super.readState(in);
        this.createdDtm = (Date)in.readObject();
        this.modifiedDtm = (Date)in.readObject();
        this.type = (String)in.readObject();
        this.children = in.readObject();
        this.events = in.readObject();
        this.primaryParent = in.readObject();
        this.secondaryParent = in.readObject();
        this.userCreated = in.readObject();
        this.userModified = in.readObject();
    }

}
