CREATE TABLE XSA_PREFERENCE (DEFAULT_VALUE VARCHAR(1024) NULL, DESCRIPTION VARCHAR(1024) NOT NULL, ID INTEGER NOT NULL, PREF_KEY VARCHAR(256) NOT NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_USER (CREATED_DTM TIMESTAMP NOT NULL, CREATED_USER_ID INTEGER NOT NULL, DISPLAYED_NAME VARCHAR(256) NOT NULL, EMAIL_ADDRESS VARCHAR(256) NOT NULL, ID INTEGER NOT NULL, MODIFIED_DTM TIMESTAMP NOT NULL, MODIFIED_USER_ID INTEGER NOT NULL, PASSWORD VARCHAR(256) NOT NULL, USERNAME VARCHAR(256) NOT NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_RELATIONSHIP (CREATED_DTM TIMESTAMP NOT NULL, CREATED_USER_ID INTEGER NOT NULL, ID BIGINT NOT NULL, MODIFIED_DTM TIMESTAMP NOT NULL, MODIFIED_USER_ID INTEGER NOT NULL, PRIMARY_PARENT_ID BIGINT NULL, SECONDARY_PARENT_ID BIGINT NULL, TYPE VARCHAR(4) NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_PERSON_IDENTITY (CREATED_DTM TIMESTAMP NOT NULL, CREATED_USER_ID INTEGER NOT NULL, END_DATE BIGINT NULL, ID BIGINT NOT NULL, MODIFIED_DTM TIMESTAMP NOT NULL, MODIFIED_USER_ID INTEGER NOT NULL, PERSON_ID BIGINT NOT NULL, START_DATE BIGINT NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_PERSON (ADDITIONAL_INFO CLOB NULL, CREATED_DTM TIMESTAMP NOT NULL, CREATED_USER_ID INTEGER NOT NULL, GENDER VARCHAR(8) NULL, GENDER_DESC VARCHAR(1024) NULL, ID BIGINT NOT NULL, MODIFIED_DTM TIMESTAMP NOT NULL, MODIFIED_USER_ID INTEGER NOT NULL, PARENT_RELATIONSHIP_ID BIGINT NULL, PRIMARY_IDENTITY_ID BIGINT NOT NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_USER_PREFERENCE (ID INTEGER NOT NULL, PREFERENCE_ID INTEGER NOT NULL, PREF_VALUE VARCHAR(1024) NULL, USER_ID INTEGER NOT NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_PERSON_EVENT (APPROXIMATION VARCHAR(8) NULL, CREATED_DTM TIMESTAMP NOT NULL, CREATED_USER_ID INTEGER NOT NULL, DTM BIGINT NOT NULL, ID BIGINT NOT NULL, LOCATION_DESC VARCHAR(256) NULL, MODIFIED_DTM TIMESTAMP NOT NULL, MODIFIED_USER_ID INTEGER NOT NULL, ORIGINAL_DATE VARCHAR(256) NULL, PERSON_ID BIGINT NOT NULL, PRECISION VARCHAR(8) NOT NULL, TYPE VARCHAR(8) NOT NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_PERSON_NAME (CREATED_DTM TIMESTAMP NOT NULL, CREATED_USER_ID INTEGER NOT NULL, ID BIGINT NOT NULL, MODIFIED_DTM TIMESTAMP NOT NULL, MODIFIED_USER_ID INTEGER NOT NULL, NAME VARCHAR(128) NOT NULL, PERSON_IDENTITY_ID BIGINT NOT NULL, SEQ_NUM SMALLINT NOT NULL, TYPE VARCHAR(16) NOT NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_PERSON_REFERENCE (CREATED_DTM TIMESTAMP NOT NULL, CREATED_USER_ID INTEGER NOT NULL, EXCERPT CLOB NULL, ID BIGINT NOT NULL, LOCATION_IN_DOC VARCHAR(256) NULL, MODIFIED_DTM TIMESTAMP NOT NULL, MODIFIED_USER_ID INTEGER NOT NULL, ORIGINAL_URL VARCHAR(1024) NULL, PERSON_ID BIGINT NOT NULL, PRIMARY KEY (ID))
;

CREATE TABLE XSA_RELATIONSHIP_EVENT (APPROXIMATION VARCHAR(8) NULL, CREATED_DTM TIMESTAMP NOT NULL, CREATED_USER_ID INTEGER NOT NULL, DTM BIGINT NULL, ID BIGINT NOT NULL, LOCATION_DESC VARCHAR(256) NULL, MODIFIED_DTM TIMESTAMP NOT NULL, MODIFIED_USER_ID INTEGER NOT NULL, ORIGINAL_DATE VARCHAR(256) NULL, PRECISION VARCHAR(8) NULL, RELATIONSHIP_ID BIGINT NOT NULL, TYPE VARCHAR(32) NULL, PRIMARY KEY (ID))
;

ALTER TABLE XSA_USER ADD FOREIGN KEY (CREATED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_USER ADD FOREIGN KEY (MODIFIED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_RELATIONSHIP ADD FOREIGN KEY (PRIMARY_PARENT_ID) REFERENCES XSA_PERSON (ID)
;

ALTER TABLE XSA_RELATIONSHIP ADD FOREIGN KEY (SECONDARY_PARENT_ID) REFERENCES XSA_PERSON (ID)
;

ALTER TABLE XSA_RELATIONSHIP ADD FOREIGN KEY (CREATED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_RELATIONSHIP ADD FOREIGN KEY (MODIFIED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON_IDENTITY ADD FOREIGN KEY (PERSON_ID) REFERENCES XSA_PERSON (ID)
;

ALTER TABLE XSA_PERSON_IDENTITY ADD FOREIGN KEY (CREATED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON_IDENTITY ADD FOREIGN KEY (MODIFIED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON ADD FOREIGN KEY (PRIMARY_IDENTITY_ID) REFERENCES XSA_PERSON_IDENTITY (ID)
;

ALTER TABLE XSA_PERSON ADD FOREIGN KEY (PARENT_RELATIONSHIP_ID) REFERENCES XSA_RELATIONSHIP (ID)
;

ALTER TABLE XSA_PERSON ADD FOREIGN KEY (CREATED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON ADD FOREIGN KEY (MODIFIED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_USER_PREFERENCE ADD FOREIGN KEY (PREFERENCE_ID) REFERENCES XSA_PREFERENCE (ID)
;

ALTER TABLE XSA_USER_PREFERENCE ADD FOREIGN KEY (USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON_EVENT ADD FOREIGN KEY (PERSON_ID) REFERENCES XSA_PERSON (ID)
;

ALTER TABLE XSA_PERSON_EVENT ADD FOREIGN KEY (CREATED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON_EVENT ADD FOREIGN KEY (MODIFIED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON_NAME ADD FOREIGN KEY (PERSON_IDENTITY_ID) REFERENCES XSA_PERSON_IDENTITY (ID)
;

ALTER TABLE XSA_PERSON_NAME ADD FOREIGN KEY (CREATED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON_NAME ADD FOREIGN KEY (MODIFIED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON_REFERENCE ADD FOREIGN KEY (PERSON_ID) REFERENCES XSA_PERSON (ID)
;

ALTER TABLE XSA_PERSON_REFERENCE ADD FOREIGN KEY (CREATED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_PERSON_REFERENCE ADD FOREIGN KEY (MODIFIED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_RELATIONSHIP_EVENT ADD FOREIGN KEY (RELATIONSHIP_ID) REFERENCES XSA_RELATIONSHIP (ID)
;

ALTER TABLE XSA_RELATIONSHIP_EVENT ADD FOREIGN KEY (CREATED_USER_ID) REFERENCES XSA_USER (ID)
;

ALTER TABLE XSA_RELATIONSHIP_EVENT ADD FOREIGN KEY (MODIFIED_USER_ID) REFERENCES XSA_USER (ID)
;

CREATE SEQUENCE pk_xsa_person_event START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_person_name START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_relationship_event START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_user_preference START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_relationship START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_person_reference START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_preference START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_person_identity START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_user START WITH 200 INCREMENT BY 20 CACHE 1
;

CREATE SEQUENCE pk_xsa_person START WITH 200 INCREMENT BY 20 CACHE 1
;
