SET DATABASE REFERENTIAL INTEGRITY FALSE;

INSERT INTO PUBLIC.XSA_PREFERENCE (ID, KEY, DESCRIPTION, DEFAULT_VALUE) VALUES (1, 'ANCESTORS_VIEW_DEPTH', 'Starting number of generations displayed in AncestorsView', '5');

INSERT INTO XSA_USER (CREATED_DTM, CREATED_USER_ID, DISPLAYED_NAME, EMAIL_ADDRESS, ID, MODIFIED_DTM, MODIFIED_USER_ID, PASSWORD, USERNAME) VALUES (NOW(), 1, 'Admin', 'invalid@email', 2, NOW(), 1, '8464b7b12a7524ec4f2c5e5f9d5bc51159555d55152390a9a881ccf4ed2570e0', 'admin');

commit;
